### ISSUE TITLE
Springboard rows and columns, and dock

### ISSUE THREAD

**Issue by ArchHughes** [MTACS/Lynx2#10]
Hi. I want to set a the number of rows and columns along with icon size (you have this) on my 6s+. Today I am using Springtomize 5 for this on ios13. I also want to set rows and columns and icon size in folders. Thanks!

**Comment by MTACS** [comment]
This will come eventually, however from what I've seen setting a custom amount messes up the layout in so many ways, at least using the methods that worked on iOS 13, not sure if its due to different layouts for library, homescreen... or widgets, I'm still looking 👍

**Comment by ArchHughes** [comment]
Thanks much.  I appreciate the feedback.  I’m anxious to go to IOS14, but dread the massive icons and many pages of icons that stock IOS requires.  I prefer them all on the first page and with lesser used apps in my own folders (instead of weird app lib folders that Apple has created).

 

Arch

**Comment by MTACS** [comment]
Everything other than homescreen columns and rows have been implemented in 2.0.3. Homescreen custom values still conflict with the layout of the App Library and will be updated when I find a way to separate the two

**Comment by ArchHughes** [comment]
Just tie the row x column change to hiding the app library.
