### ISSUE TITLE
Triple Tap Lock

### ISSUE THREAD

**Issue by luisrbpereira** [MTACS/Lynx2#100]
Beside double tap lock, please add triple tap lock please

**Comment by MTACS** [comment]
Added in 2.0.8

**Comment by luisrbpereira** [comment]
Hi,

Triple tap lock is in 2.0.8? Can´t find the option to enable it.

Thanks

De: D.F. ***@***.***>
Enviada: 17 de abril de 2021 18:11
Para: MTACS/Lynx2 ***@***.***>
Cc: luisrbpereira ***@***.***>; Author ***@***.***>
Assunto: Re: [MTACS/Lynx2] Triple Tap Lock (#100)


Added in 2.0.8
