### ISSUE TITLE
Lockscreen font opacity

### ISSUE THREAD

**Issue by C1NY** [MTACS/Lynx2#102]
**Describe the bug**

Lynx2/lockscreen settings, I've lighten the "time" font to say 0.30% and works fine until I plug my phone to charge/remove charger, the font opacity returns to default 1.0%. Any way you can look into that.

Thanks bro.

**To Reproduce**

Plug your phone to charger, Qi wireless charge, wait a while then unplug, remove from Qi charger, lock or swipe down for notifications (LS).

**Expected behavior**

Would be nice to set the opacity of fonts and be persistent. *side note* can you add the functionality of customizing font colors with built in color picker, with option to save custom sets.

**Screenshots**

**Platform (please complete the following information):**
 - Device: (iPhone X)

iPhone XS Max

 - Injection: (substrate, libhooker)

Substrate (unc0ver)

 - iOS Version: (iOS 14.1)

iOS 14.3

 - Package Manager: (Zebra, Installer, Cydia, Sileo)

Cydia

**Comment by MTACS** [comment]
Fixed in 2.0.8
