### ISSUE TITLE
App Library List View Edit Button

### ISSUE THREAD

**Issue by cervixexplosion** [MTACS/Lynx2#105]
**Feature Request**

Could you add an Edit button to the App Library List View for deleting apps? Currently I have to pull the app to the home screen to delete the app but would great if I could just do it right from the App Library List View

**Comment by MTACS** [comment]
I'll add to option to remove app and move to homescreen from the list view

**Comment by MTACS** [comment]
Hope this is similar to what you're looking for 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13209789/114616161-8b2c2e80-9c74-11eb-9c04-00ae22e3194a.gif)

**Comment by cervixexplosion** [comment]
Yes! Looks great!
