### ISSUE TITLE
“Hide alert banner” switch is greyed out

### ISSUE THREAD

**Issue by dinnermanac** [MTACS/Lynx2#106]
**Describe the bug**
Title says it all.

**To Reproduce**
I’m on Lynx 2 v2.0.7. 
iOS 14.3 Taurine 1.0.3 if this matters.
I also have an iPad Pro with the same issue. Lynx 2 is the only tweak I have on the iPad, so I think compatibility error with other tweaks would not be the cause in my case. 
![D20EF69E-3E7C-4E14-A0E8-C75A7ACBE2F3](https://user-images.githubusercontent.com/82518858/114716431-9f505880-9d66-11eb-8f86-c2ae98c772a9.jpeg)

**Screenshots
Attached

**Platform (please complete the following information):**
 - Device: (iPhone XS Max
 - Injection: (libhooker
 - iOS Version: (iOS 14.3
 - Package Manager: (Sileo

**Comment by MTACS** [comment]
It has been disabled as it randomly broke, and will be enabled again once a fix is found

**Comment by MTACS** [comment]
Fixed it in 2.0.8, doesn't affect AirPods or Bluetooth alerts yet but paste has been disabled
