### ISSUE TITLE
Stacked widget

### ISSUE THREAD

**Issue by DWINGSP** [MTACS/Lynx2#121]
The bug: Stacked widgets, you cannot scroll to the 2nd one it flies back to widget 1 in the stack.  

Reproduce: use a stacked widget.  

Expected behavior: when you scroll to 2nd widget, you can see the second widget

**Screenrecording**

**Platform (please complete the following information):**
 - Device: (iPhone 12 pro max)
 - Injection: (libhooker)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Zebra, Sileo)

https://user-images.githubusercontent.com/82986824/115641458-23668b00-a2e7-11eb-8b94-9f447df5127c.MP4

**Comment by LanceLePants** [comment]
Came to report this as well. All Smart Stack widgets seem to be scrolling by 2 instead of 1 in Today View as well in v2.0.9

**Comment by DWINGSP** [comment]
Sure hope there’s an update to fix this cause I didn’t see one

**Comment by MTACS** [comment]
Update will be released soon
