### ISSUE TITLE
Hiding home screen app labels also hides App Library category labels.

### ISSUE THREAD

**Issue by systox** [MTACS/Lynx2#122]
**Describe the bug**
Hiding icon labels on Home Screen also hides category labels on App Library.

**Expected behavior**
Only home screen app labels should be hidden.

**Platform (please complete the following information):**
 - Device: (iPhone 11 pro max)
 - Injection: (substrate, substitute?)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Zebra)

**Comment by MTACS** [comment]
Fixed in 2.1.1
