### ISSUE TITLE
Crash to Safe mode when swiping pages with just tweak enabled on IOS 14.3, iP 12 pro max

### ISSUE THREAD

**Issue by Doyle884** [MTACS/Lynx2#125]
**Description**
When ever I download lynx and enable it, respring and go to swipe to another page, it crashes to safe mode. 

**To Reproduce**
1. Enable lynx and respring 
2. Go to Home Screen and swipe page 

**Expected behavior**
It's supposed to go to next page ;p

**Platform (please complete the following information):**
 - Device: (iPhone 12 Pro Max)
 - Injection: (substrate, libhooker)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Cydia)

**Comment by MTACS** [comment]
Sounds like a conflict, could you attach a crashlog?

**Comment by SarahH12099** [comment]
Closing due to the lack of response and no crashlog provided, feel free to re-open with a crashlog and make sure you are on the latest Lynx 2 please.
