### ISSUE TITLE
broken on ios 14.5

### ISSUE THREAD

**Issue by senternathan** [MTACS/Lynx2#126]
**Describe the bug**
sends device to safemode
**To Reproduce**
turn lynx on and respring
**Expected behavior**
resprings and doesn't go into safemode
**Screenshots**

**Platform (please complete the following information):**
 - Device: (iPhone 7+)
 - Injection: (libhooker)
 - iOS Version: (iOS 14.5)
 - Package Manager: (Sileo (odysseyra1n))

**Comment by MTACS** [comment]
Please attach a crashlog
