### ISSUE TITLE
It is recommended to add functionality

### ISSUE THREAD

**Issue by anruan123** [MTACS/Lynx2#131]
**Feature Request**

Hello developer, in the second point of advice, I hope you can update support.

1. Disable the home screen drop-down search bar.

2. Increased face unlock successfully automatically enters the home screen.

3. Add any page under the screen to open control center.

Thank you！

Please make sure the request is possible and related to the existing theme of Lynx features. In addition, please check the current list of requested features to make sure there are no duplicates

**Comment by SarahH12099** [comment]
The first feature is already coming in the next release version of Lynx 2, please post the other 2 in your previous post rather then posting again #130
