### ISSUE TITLE
Disable spotlight and remove folder background 

### ISSUE THREAD

**Issue by Xeroooo** [MTACS/Lynx2#139]
Feature Request**

An option to disable the entire spotlight and another to remove folder background

**Comment by MTACS** [comment]
Both are options that already exist in Lynx, please use the search bar of the appropriate section to make sure it doesn't already exist before submitting a request. The changelog is always updated as well, and details each recently added option 
![IMG_4310](https://user-images.githubusercontent.com/13209789/117836616-bdff1d80-b246-11eb-88a8-d69c752e99e7.jpg)
![IMG_4311](https://user-images.githubusercontent.com/13209789/117836635-c0617780-b246-11eb-9c41-8d440d1959c3.jpg)
