### ISSUE TITLE
App Library Swipe Disable

### ISSUE THREAD

**Issue by ThebigdeLer** [MTACS/Lynx2#145]
**Feature Request**

Please make sure the request is possible and related to the existing theme of Lynx features. In addition, please check the current list of requested features to make sure there are no duplicates

Hey there I love all the features that you have added into Lynx! I’m not sure if you remember me but we used to chat on Reddit! I requested a tweak to disable vibration systemwide and then you realized that was already built into IOS😂👍🏼 Anyway I was wondering if you could implement a feature into the App Library section where you can Disable the List Mode and the search activation completely?

**Comment by MTACS** [comment]
Added in 2.2
