### ISSUE TITLE
Folders disappearing

### ISSUE THREAD

**Issue by Yuri989** [MTACS/Lynx2#152]
**Describe the bug**
The folder icons keep disappearing on springboard

**To Reproduce**
It happens randomly when I scroll through my different pages on springboard and have the setting "Hide folder Icon Background " activated

**Expected behavior**
To have my folders not disappear 

**Screenshots**
Normal 
![image](https://user-images.githubusercontent.com/77815562/119279759-c454a880-bbfb-11eb-9b43-41a2f81aedf9.jpeg)
Not Normal
![image](https://user-images.githubusercontent.com/77815562/119279770-d20a2e00-bbfb-11eb-8283-f54e7840f4c8.jpeg)

**Platform (please complete the following information):**
 - Device: Iphone 7
 - Injection: libhooker
 - iOS Version: iOS 14.4
 - Package Manager: Sileo

**Comment by SarahH12099** [comment]
That means you have another tweak interfering as per we can tell by your homescreen setup.
