### ISSUE TITLE
Show exact time 24h mode

### ISSUE THREAD

**Issue by rml9ty** [MTACS/Lynx2#159]
There’s a (I suppose) bug under Phone, Calls, Show exact time, 24h mode. It displays, for instance, 17:35 PM. Isn’t that redundant? Either PM or 24h mode. 

Thanks for keeping lynx up to date!

Using lynx 2.2, iPhone X on 14.3

**Comment by SarahH12099** [comment]
This has been fixed in the upcoming v2.2.1 release
