### ISSUE TITLE
Report Browser issues caused by Lynx 2(version 2.3)

### ISSUE THREAD

**Issue by TimeElapse-ES** [MTACS/Lynx2#168]
**Describe the bug**

After updating the latest version of Lynx 2 (version: 2.3), it will cause the browser to crash.

**To Reproduce**

Only Lynx is enabled, none of the options in it are enabled(With Alook Browser)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/95919970/145579045-df51f4d3-5ef2-4169-9b61-6ac6d1bbc0fa.png)
![image](https://user-images.githubusercontent.com/95919970/145579075-f669eedb-3029-47ed-af72-2bb612f1e4be.png)

**Platform (please complete the following information):**

 - Device: (iPhone 12 Pro Max)
 - Injection: (Unc0ver+Fugu 14, substrate,)
 - iOS Version: (iOS 14.4.2)
 - Package Manager: (Cydia,Zebra)

**Comment by MTACS** [comment]
I'll add
