### ISSUE TITLE
App Library Labels and Badges disappearing

### ISSUE THREAD

**Issue by TheIronboy** [MTACS/Lynx2#17]
**Describe the bug**
when i install and enable lynx 2 the labels and the badges on the app library disappears

**To Reproduce**
download lynx 2, install it, and ONLY turn on the tweak in settings

**Expected behavior**
if i enable only the tweak without anything else, it should do nothing

**Screenshots**
![79726A52-2D74-4B0E-89B3-2F76C4B853BB](https://user-images.githubusercontent.com/66006359/103826120-86088380-5076-11eb-88bd-c3ec2c6d244a.png)

**Platform (please complete the following information):**
 - Device: iPhone X
 - Injection: Substrate
 - iOS Version: iOS 14.3
 - Package Manager: Zebra

**Comment by MTACS** [comment]
Fixed in 2.0.3

**Comment by TheIronboy** [comment]
i don’t see any update on the twickd repo

Luca Giordano
