### ISSUE TITLE
Features not working on 14.8

### ISSUE THREAD

**Issue by ramirojm3** [MTACS/Lynx2#171]
**Describe the bug**
There are 3 features not working:
1. MagSafe animation doesn’t show when I plug my phone 
2. Date under time is buggy
3. “Force enable camera” is not working

**To Reproduce**
1. I enabled “native animation” on MagSafe section, then made a full respring and plugged my phone but still shows the normal animation
2. I enabled “date under time” for the status bar, made full respring and it works, but after opening any app it disappears, even if I get back to HomeScreen, and appears for seconds and disappears again
3. After disabling camera swipe on lockscreen and enabling “force enabling camera” the toggle is usable (you can press it and there’s haptic feedback) but it doesn’t open the camera 

**Expected behavior**
1. With MagSafe option, I expected to see MagSafe animation when I plug my phone 
2. With date under time I expected to see anytime anywhere the date under time 
3. With “force enabling camera” I expected to be able to open the camera pressing the toggle with swipe to open option disabled 

**Screenshots**

**Platform (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - Injection: substitute
 - iOS Version: iOS 14.8
 - Package Manager: Installer, Cydia

**Comment by MTACS** [comment]
Apple must've changed their wireless accessory stuff around a lot, I'm still trying to see the difference between 14.8 and my daily 14.3, hopefully I can force it to show another way. 

I'll have to test with Corellium for the date under time as my only 14.8 device is a 6s.

Lockscreen force enable camera working fine, as far as I know its exactly the same classes as a notched device, I'll test on a notched 14.8 device as well
