### ISSUE TITLE
Disable floaty dock in certain apps 

### ISSUE THREAD

**Issue by Suavepapi** [MTACS/Lynx2#173]
**Feature Request**
Hi, thanks for the awesome work being done for this tweak. I know you already added a function to disable floaty dock for all apps. But would it be possible to just disable it in certain apps. For example in games. I ran into switching to a different app because of floaty being activated. 
Thanks again. And have a great day!

Please make sure the request is possible and related to the existing theme of Lynx features. In addition, please check the current list of requested features to make sure there are no duplicates

**Comment by MTACS** [comment]
I'll take a look at adding it

**Comment by MTACS** [comment]
Added in 2.3.3
