### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tvalde** [MTACS/Lynx2#180]
**Feature Request**

Can you add the option to remove the data network icon from the statusbar and to hide the tool bar in the apple notes app.

**Comment by MTACS** [comment]
I've added the data option to the next update, by toolbar so you mean at the bottom of a note? ![image](https://user-images.githubusercontent.com/13209789/208916715-251865c6-90c5-4b23-9163-5574261f3ae3.png)

**Comment by tvalde** [comment]
The toolbar that shows up when the keyboard pops up here a pic.
