### ISSUE TITLE
Phone Dialer

### ISSUE THREAD

**Issue by tvalde** [MTACS/Lynx2#181]
**Feature Request**

Hide the Favorite Phone Tabs in the dialer

**Comment by MTACS** [comment]
Added options to toggle each tab bar item ![image](https://user-images.githubusercontent.com/13209789/209137610-5ea7cef0-c2a0-4181-ac52-7129fe73a3fe.png)
![image](https://user-images.githubusercontent.com/13209789/209137629-c6f8d791-e503-411e-b2ae-8532d2b92a84.png)
