### ISSUE TITLE
Lynx 2 causes my 7 Plus to go into Safe Mode

### ISSUE THREAD

**Issue by casungo** [MTACS/Lynx2#21]
**Describe the bug**
When I install Lynx 2 via Zebra, after the required respring, the phone goes into Safe Mode. Even after a respring with the "Restart" button on the Safe Mode popup, the iPhone returns into the same Safe Mode.

**To Reproduce**
1. Install Lynx
2. Respring

**Expected behavior**
The iPhone should respring with no errors and work as normal

**Screenshots**
N/A

**Platform:**
 - Device: iPhone 7 Plus
 - Injection: Substitute 2
 - iOS Version: iOS 14.3
 - Package Manager: Zebra

**Comment by MTACS** [comment]
Sounds like a conflicting tweak, would you be able to install Cr4shed and send a crashlog?

**Comment by casungo** [comment]
So, I don't know how I fixed this, but apparently Lynx 2 wasn't installed correctly or something along those lines.
Sorry for the trouble! Closing the non-issue :P
