### ISSUE TITLE
Hide Battery View on Lockscreen Not Working

### ISSUE THREAD

**Issue by dinouse** [MTACS/Lynx2#22]
**Describe the bug**
When i enabled Hide Battery View on lockscreen it doesnt hide. But just appeared when i charged it.
**To Reproduce**

**Expected behavior**
The big Battery view should gone whenever charging.

**Screenshots**
![image](https://user-images.githubusercontent.com/62304158/105149357-6c6b3f80-5b3e-11eb-94ab-de50628d6519.png)
**Platform (please complete the following information):**
 - Device: iPhone 6s
 - Injection: Checkra1n 
 - iOS Version: 14.0
 - Package Manager: Cydia

**Comment by SarahH12099** [comment]
This issue has been fixed in the upcoming 2.1.1 release
