### ISSUE TITLE
A few bugs...

### ISSUE THREAD

**Issue by B777-9X** [MTACS/Lynx2#23]
Firstly, the most important bug is that am experiencing slower app loading times. It’s taking forever to open safari and other applications.

Secondly, when selecting ‘show percent in battery’ it doesn’t show when charging. It’s not possible to know the percentage when charging the phone.

Jailbroken IPhone 7 Plus GSM
iOS 14.3

**Comment by B777-9X** [comment]
Also I am getting a noticeable battery drain. Other than that, everything seems alright

**Comment by SarahH12099** [comment]
Closed due to them being fixed.
