### ISSUE TITLE
Lynx 2 crashes right after being enabled. I am on ios 14.2 iphone 7

### ISSUE THREAD

**Issue by Sunny-Ade** [MTACS/Lynx2#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Device: (iPhone X)
 - Injection: (substrate, libhooker)
 - iOS Version: (iOS 14.1)
 - Package Manager: (Zebra, Installer, Cydia, Sileo)

**Comment by MTACS** [comment]
Could I get a crashlog or any other context?

**Comment by Sunny-Ade** [comment]
/var/mobile/Library/Logs/CrashReporter/SpringBoard-2021-02-06-201439.ipsOn

**Comment by Sunny-Ade** [comment]
Hi,I hope that this is what you asked for. Thanks for your speedy response

**Comment by MTACS** [comment]
That's just the path of it, could you upload it to Dropbox/pastebin or something similar?

**Comment by Sunny-Ade** [comment]
I tried,but could not download any app from the app store,so i could not
use dropbox. Sorry,i don't know how else i could be transfered

**Comment by SarahH12099** [comment]
Closed due to inactivity
