### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by K1llah03z** [MTACS/Lynx2#261]
Please fill out all fields with as much detail as possible

**Describe the bug:**
When selecting A custom color for home screen Apps the label completely disappears 
**Process To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Platform (please complete the following information):**
 - Device: iPhone 12 pro max
 - Injection: (substrate/substitute, libhooker, ellekit)
 - iOS Version:
iOS 15.4.1 using Dopamine Jailbreak with ellkit

**Comment by K1llah03z** [comment]
![28528637-E25B-429B-A89A-509EE2297B17](https://github.com/MTACS/Lynx2/assets/47945161/b1d852a5-ef77-48db-9351-db034fc105fd)

**Comment by K1llah03z** [comment]
![F5DB54B6-4444-4AF7-B4BC-A4FAC71D0F42](https://github.com/MTACS/Lynx2/assets/47945161/f9725cb1-72f7-42c1-88be-a5de02630ce3)

**Comment by MTACS** [comment]
Are you swiping on the cell to set the color?

**Comment by K1llah03z** [comment]
Yeah! Once activated It hides the labels I've tried A few different Colors and transparency Setting it just disappears. When selecting Based off app color it shows up!

**Comment by K1llah03z** [comment]
Lynx 2.4.10 has fixed The issue.  Will close now
