### ISSUE TITLE
Translucent Settings app

### ISSUE THREAD

**Issue by iamn0tdev** [MTACS/Lynx2#269]
Settings app view with customizable blurred background.

**Comment by D1TCHD0C0331** [comment]
I would love to have this feature also a way to make the settings tiles translucent

**Comment by MTACS** [comment]
Has been added to the upcoming 2.4.7 update ![image](https://github.com/MTACS/Lynx2/assets/13209789/216b8ae4-8988-413b-be8e-9556339507b9)

**Comment by D1TCHD0C0331** [comment]
Awesome thank you

**Comment by iamn0tdev** [comment]
> Has been added to the upcoming 2.4.7 update ![image](https://private-user-images.githubusercontent.com/13209789/298287999-216b8ae4-8988-413b-be8e-9556339507b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjI5MTcsIm5iZiI6MTcwNjYyMjYxNywicGF0aCI6Ii8xMzIwOTc4OS8yOTgyODc5OTktMjE2YjhhZTQtODk4OC00MTNiLWJlOGUtOTU1NjMzOTUwN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEzNTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzgwMGVjYWEyOGQ1YTc2NDZmMWIxMjAzMzY4NjIxYWFkNWNiMjE5NDVhZDg5N2Q1MmYwYjRiNzcyZWM3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AKfImrrS7TTyh2LksJHyeIu-g965eJwrQUlKqyT22Q8)

Don’t work on iOS 14.3, Taurine, Lynx v2.4.7
