### ISSUE TITLE
The volume percentage on the cc is broken

### ISSUE THREAD

**Issue by FreshDialSoap** [MTACS/Lynx2#321]
iPhone 13 Pro Max iOS 16.1.2. Dopamine 2.0
The volume slider percentage in the cc won’t appear when connected to a Bluetooth device. Example AirPods Pro 2
![CA9671DC-01AF-487B-8D61-F8A0516C12A8](https://github.com/MTACS/Lynx2/assets/104802755/69a35cfe-e739-4e0e-b2d8-3f9040500c33)

**Comment by MTACS** [comment]
Fixed in upcoming 2.4.9 update
