### ISSUE TITLE
Floating dock & Icon transparency Issue

### ISSUE THREAD

**Issue by NF8S** [MTACS/Lynx2#326]
Before i talk about the issue i want to clarity that
this issue still is present while solely using the latest version of Lynx

While using the Floating dock option along with setting the transparency lower, one of the app icons in the dock along with one of the recent app icon seems to have full transparency whilst all the other icons have a lower transparency.

To reproduce the issue simply turn on floating dock in the Springboard section, & lower the transparency of app icons in the Icons section.

![EA30AB28-D4FC-4BB5-AE05-EF19B58522D9](https://github.com/MTACS/Lynx2/assets/160570848/96e2d49c-2355-4c67-a324-dd143ae3a550)

 - Device: iPhone XR
 - Jailbreak: Dopamine (latest version)
 - iOS Version: iOS 15.1

-Thank you for your amazing work!

**Comment by MTACS** [comment]
Fixed in upcoming 2.4.9 update
