### ISSUE TITLE
Status bar date/time

### ISSUE THREAD

**Issue by InFlamesHell** [MTACS/Lynx2#330]
Hi,
The "Display date under time" feature basically makes the time hidden at the top of the screen and only the date is visible. (iPhone SE 16.5.1)
Springtomize had the option to set the date next to the time, so it looks like this in the statusbar (or custom format was also supported):
Feb 20 - 14:01
Can the same be done with Lynx?
Thanks,

**Comment by MTACS** [comment]
Fixed/Added in upcoming 2.4.9 update

**Comment by InFlamesHell** [comment]
Confirmed fixed with 2.4.10
