### ISSUE TITLE
Issue with blank widgets list and cant access widgets in lynx settings

### ISSUE THREAD

**Issue by joseph22baker** [MTACS/Lynx2#356]
Please fill out all fields with as much detail as possible

**Describe the bug:**
When lynx is activated, there are three blank titled widgets at the top of my screen battery widget/shortcuts widget/some type of maps widget. In addition the widgets section wont open under tweak lynx settings.

**Screenshots:**
https://imgur.com/a/0yWhwHv

**Platform (please complete the following information):**
 - Device: iPhone 14 pro max
 - Jailbreak: Dopamine 2 
 - iOS Version: 16.1

**Comment by Hamadtov503** [comment]
I experienced the same issue
