### ISSUE TITLE
Install issue - Missing Lynx 2 icon

### ISSUE THREAD

**Issue by ungloved9166** [MTACS/Lynx2#365]
Just bought and installed the app and the Cephei dependency using Sileo on an iPhone 14, running 16.3.1. I hit respring, and came back to the springboard but dont see the app anywhere. Spotlight doesnt see it, but it says its installed in Sileo. 

 - Device: 14
 - Jailbreak: Dopamine 2.0.9
 - iOS Version: 16.3.1

**Comment by MTACS** [comment]
It show in Settings by default, if you would like a Homescreen icon, you can download Lynx application from my personal repo https://mtac.app/repo

**Comment by ungloved9166** [comment]
Weird.. i looked everywhere in settings and nothing. The one from your repo showed up in the homescreen but no tweaks are applying. Switched on the sections and some tweaks in those sections, pressed apply and no luck. Respring, nothing. I have Cephei still installed. Anything else I could look at? Thanks. Sent from my iPhoneOn Mar 8, 2024, at 9:35 PM, D.F. ***@***.***> wrote:﻿
It show in Settings by default, if you would like a Homescreen icon, you can download Lynx application from my personal repo https://mtac.app/repo

**Comment by ungloved9166** [comment]
Weird.. i looked everywhere in settings and nothing. The one from your repo showed up in the homescreen but no tweaks are applying. Switched on the sections and some tweaks in those sections, pressed apply and no luck. Respring, nothing. I have Cephei still installed. Anything else I could look at? Thanks.

**Comment by ungloved9166** [comment]
Found what was missing.. tweak injection is not on by default on dopamine! All good now thanks!
