### ISSUE TITLE
App Lock can be bypassed with Siri Suggestions

### ISSUE THREAD

**Issue by Kai-Denzel-Jane** [MTACS/Lynx2#366]
When locking an app on your home screen (SpringBoard) if you attempt to open it from Siri Suggestions it doesn't prompt for you to unlock it.

**Steps to reproduce:**

1. Lock an App
2. Open Siri Suggestions
3. Search for the app you locked
4. Press the app and it opens

 - **Device:** iPhone 8
 - **Jailbreak:** Dopamine (Latest)
   
 - **iOS Version:** 16.1.2

**Comment by MTACS** [comment]
Are you talking about the Siri widget, or the suggestions that popup in Spotlight?

**Comment by Kai-Denzel-Jane** [comment]
> Are you talking about the Siri widget, or the suggestions that popup in Spotlight?

I was referring to the spotlight suggestions and you marked as fixed so I assume you figured it out

**Comment by MTACS** [comment]
Yes, somehow missed them when I originally wrote the code, it'll be included in the next update

**Comment by Kai-Denzel-Jane** [comment]
> Yes, somehow missed them when I originally wrote the code, it'll be included in the next update

Alright thanks also forgot to mention it seems the apps are unlocked after a respring is this fixable?

**Comment by Kai-Denzel-Jane** [comment]
> > Yes, somehow missed them when I originally wrote the code, it'll be included in the next update
> 
> Alright thanks also forgot to mention it seems the apps are unlocked after a respring is this fixable?

Actually I just tried it and they remained locked not sure what happened earlier
