### ISSUE TITLE
Display icon as a folder

### ISSUE THREAD

**Issue by tvalde** [MTACS/Lynx2#374]
Display icons as a folder are chopped I’ve included a screenshot

**Platform**
 - Device: iPad Air
 - Jailbreak: unc0ver
 - iOS Version: 14.4

![5268BD73-8725-4A97-8FEE-BE461B6AB130](https://github.com/MTACS/Lynx2/assets/121121821/2a3d2f37-a16f-4c4d-98b2-2105b64733a7)

**Comment by MTACS** [comment]
Do you have a custom icon scale set in Snowboard?

**Comment by tvalde** [comment]
No everything is unchecked

**Comment by tvalde** [comment]
Works great on iPhone X 16.6 and iPhone 12PM 14.2

**Comment by tvalde** [comment]
Thanks for adding these features
