### ISSUE TITLE
Lynx 2 Bug Report

### ISSUE THREAD

**Issue by CaseyCZ** [MTACS/Lynx2#39]
**Describe the bug**
Widgets - Hide Search Bar - Not work
System wide - place Face Down to Lock  - Not work

**Platform (please complete the following information):**
 - Device: (iPhone X)
 - Injection: (substrate)
 - iOS Version: (iOS 14.3)
 - Package Manager: ( Cydia)

**Comment by MTACS** [comment]
Widgets search bar was fixed in 2.0.4, place Face Down to Lock should work, do you have a case or anything blocking the front proximity sensor?

**Comment by SarahH12099** [comment]
Closed due it now being fixed and no further response
