### ISSUE TITLE
[Bug] Running indicator offset

### ISSUE THREAD

**Issue by xBiei** [MTACS/Lynx2#398]
**Describe the bug:**
The running indicators' offset on the y-axis is messed up when having more than 1 recent apps.
(imo it looks like the offset value is static so whenever the floating dock becomes smaller it still keeps the same offset which makes it look wrong)

**Process To Reproduce:**
- enable running indicators in the Lynx2 settings
- open more than 1 apps

**Screenshots:**
![image](https://github.com/MTACS/Lynx2/assets/65196493/6dee8a4e-afa6-49bd-8393-f0838773d0cd)

**Platform:**
 - Device: iPhone 13 Pro
 - Jailbreak: Dopamine 2.0.11
 - iOS Version: 16.4.1

**Comment by MTACS** [comment]
Fixed in upcoming update
