### ISSUE TITLE
Lockscreen custom text not working. In lockscreen section / unlock text.

### ISSUE THREAD

**Issue by jinshah05** [MTACS/Lynx2#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Device: (iPhone X)
 - Injection: (substrate, libhooker)
 - iOS Version: (iOS 14.1)
 - Package Manager: (Zebra, Installer, Cydia, Sileo)

**Comment by MTACS** [comment]
Is the option for custom text enabled? Could you also fill out some of the form information like device, it helps a lot in testing

**Comment by jinshah05** [comment]
I have installed texttime tweak and cthulhu for this custom text on lockscreen. But After Lynx 2 installed, It's not working.

Try to delete textime tweak and recheck in lynx 2.

**Comment by jinshah05** [comment]
> Is the option for custom text enabled? Could you also fill out some of the form information like device, it helps a lot in testing

Yes custom text option enable.

**Comment by jinshah05** [comment]
> Is the option for custom text enabled? Could you also fill out some of the form information like device, it helps a lot in testing

Device: (iPhone 7)
Injection: (cydia substrate)
iOS Version: (iOS 14.2)
Package Manager: (Zebra)

**Comment by jinshah05** [comment]
Sorry. Halfipad tweak is the problem. Its working now.
