### ISSUE TITLE
YouTube Crashes with latest 2.5.1 Update

### ISSUE THREAD

**Issue by coryshaw1** [MTACS/Lynx2#412]
Please fill out all fields with as much detail as possible

**Describe the bug:**
After updating to 2.5.1 today, YouTube crashes on launch until I disable Lynx tweak injection via Choicy to YouTube.

**Process To Reproduce:**
I have a feeling it could be CarPlay-related, so I've added my CarPlay settings below.
**Screenshots:**
![IMG_5222](https://github.com/MTACS/Lynx2/assets/5014172/eae7e626-40b1-43bb-8109-86ba5ed69f39)

**Platform (please complete the following information):**
 - Device: 14 Pro Max
 - Jailbreak: 
    - Dopamine 2
 - iOS Version: 16.1.1

**KrashKop Dump**
[text-C0A1D11473DB-1.txt](https://github.com/MTACS/Lynx2/files/14910957/text-C0A1D11473DB-1.txt)

Please let me know if you need more details.

**Comment by AMlG0** [comment]
Im not sure if it’s Lynx 2 related or not, but my YouTube app also crashes immediately upon launch after the recent YouTube app update. As a temporary solution, I downgraded via AppStore ++ to the last version I was using and it works again.

**Comment by coryshaw1** [comment]
Seems that this is fixed with the latest YouTube update from today (19.14.3)
