### ISSUE TITLE
Hide/Disable “unlocked” text and glyph in non-notched devices

### ISSUE THREAD

**Issue by Luki120** [MTACS/Lynx2#43]
**Feature Request**

What the title says, ss for reference:

![image](https://user-images.githubusercontent.com/74214115/109816594-adf80b80-7c0f-11eb-9671-5cd803463060.jpeg)

**Comment by MTACS** [comment]
Is this no longer working? ![image](https://user-images.githubusercontent.com/13209789/110043444-69569800-7d15-11eb-9ac5-4fd35f071a6b.png)

**Comment by Luki120** [comment]
Yeah sorry, I missed that option. The problem is that it conflicts with iPad Status Bar style, it glitches like hell in HS and the Status Bar dissapears, all good inside apps though.
