### ISSUE TITLE
Add day of the week as a date string

### ISSUE THREAD

**Issue by jim16127** [MTACS/Lynx2#442]
Could you add support for the day of the week in the custom time/date? Normally ‘ddd’ would display the short name for day of the week and ‘dddd’ would display the full name for day of the week.

ddd = Mon
dddd = Monday

Here’s a resource for reference indicating exactly what I’m describing.

https://documentation.decisions.com/docs/custom-date-time-format-strings

**Comment by MTACS** [comment]
You can do this already by using EEE for the short version (Mon), and EEEE for the longer version (Monday). It uses a NSDateFormatter syntax instead of the one mentioned above. https://www.nsdateformatter.com/

**Comment by jim16127** [comment]
> You can do this already by using EEE for the short version (Mon), and EEEE for the longer version (Monday). It uses a NSDateFormatter syntax instead of the one mentioned above. https://www.nsdateformatter.com/

Thank you for your prompt response. Sorry for my late reply! That's excellent. I feel like I've covered this with you before. (Just forgot) Thanks again! Top notch software. I'm sure I'll find some bugs soon. Just upgraded to the latest iOS 15.
