### ISSUE TITLE
Cylinder 

### ISSUE THREAD

**Issue by drbf** [MTACS/Lynx2#46]
Lynx on iPhone 12 XS works great but causes iPhone to crash when used with the Cylinder tweak.
Thanks, Dr Frankel 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Device: (iPhone X)
 - Injection: (substrate, libhooker)
 - iOS Version: (iOS 14.1)
 - Package Manager: (Zebra, Installer, Cydia, Sileo)

**Comment by MTACS** [comment]
A fix has been added to the upcoming 2.0.4
