### ISSUE TITLE
Please add the ability to increase or decrease the size of the home screen icons as before

### ISSUE THREAD

**Issue by quangka** [MTACS/Lynx2#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Device: (iPhone X)
 - Injection: (substrate, libhooker)
 - iOS Version: (iOS 14.1)
 - Package Manager: (Zebra, Installer, Cydia, Sileo)

**Comment by quangka** [comment]
Please add the ability to increase or decrease the size of the home screen icons as before

**Comment by quangka** [comment]
Please answer me

**Comment by Luki120** [comment]
Why don't you just *wait and be patience*? He'll see it eventually.

**Comment by quangka** [comment]
Because I haven't seen a long response, sir

Vào Th 6, 5 thg 3, 2021 lúc 22:21 Luki120 <notifications@github.com> đã
viết:

**Comment by MTACS** [comment]
I’d just copy the code, but increasing icon sizes changes App Library as well as widgets on iOS 14, when I can separate them it’ll be added, just trying to avoid known issues when possible

**Comment by quangka** [comment]
Ok thanks for your positive feedback, I will look forward to the changes in
the future, good luck to you and everyone.

Vào Th 6, 5 thg 3, 2021 lúc 22:55 D.F. <notifications@github.com> đã viết:

> I’d just copy the code, but increasing icon sizes changes App Library as
> well as widgets on iOS 14, when I can separate them it’ll be added, just
> trying to avoid known issues when possible

**Comment by quangka** [comment]
Please show me how to convert to source mtac.yourepo.com/
Before that I bought it from twick source
