### ISSUE TITLE
Feature to hide this navigation and bottom tab bar lines. Like in old lynx 1.

### ISSUE THREAD

**Issue by jinshah05** [MTACS/Lynx2#5]
**Feature Request**

Please make sure the request is possible and related to the existing theme of Lynx features. In addition, please check the current list of requested features to make sure there are no duplicates

![64506](https://user-images.githubusercontent.com/49037696/102303918-40c6c980-3f82-11eb-922a-2d1bbe257245.jpg)

**Comment by MTACS** [comment]
Added in 2.0.1
