### ISSUE TITLE
Landscape Bug

### ISSUE THREAD

**Issue by mostberserk** [MTACS/Lynx2#50]
Whenever you disable rotation lock to view a video of any kind & platform & you want to check something in the Notification Center the clock is centered opposed to adjusting to the left as it usually does in stock. It overlaps music player & notifications as well.

To reproduce it just have to go into safari for example / disable rotation lock from the control center / turn the phone into landscape mode & swipe down to invoke the Notification Center & the lock will be in the center & doesn’t adjust accordingly. 

The expected behavior id assume would happen is that no matter the orientation the clock as it is should adapt to the notifications and music  player so it’s not overlapping anything. 

I’ve attached an image to show an example of no matter what it is you do, in landscape mode the clock doesn’t adjust for anything. 
![B8D32794-AC96-4EA0-AD0D-7C6EC6963E87](https://user-images.githubusercontent.com/80085540/110068024-d2083980-7d42-11eb-809c-14f7867ded21.png)

 - Device: iPhone 11
 - Injection: Substitute
 - iOS Version: iOS 14.2 
 - Package Manager: Cydia

**Comment by TheIronboy** [comment]
same problem here :(
