### ISSUE TITLE
Hide folder dots

### ISSUE THREAD

**Issue by Devilishx** [MTACS/Lynx2#58]
**Feature Request**

Please make sure the request is possible and related to the existing theme of Lynx features. In addition, please check the current list of requested features to make sure there are no duplicates

**Comment by SarahH12099** [comment]
This already exists in Lynx 2 with hide page dots option.

**Comment by falsified** [comment]
Seems bugged out in 2.4.8
![IMG_730459047914](https://github.com/MTACS/Lynx2/assets/20657172/a932c608-2712-4fab-a789-907ac27d9257)
![IMG_730458965515](https://github.com/MTACS/Lynx2/assets/20657172/2e36aa07-667b-49de-b703-f886ab498396)
