### ISSUE TITLE
Hide Swipe Up to Unlock doesn't work

### ISSUE THREAD

**Issue by nyuszika7h** [MTACS/Lynx2#61]
**Describe the bug**
Hide Swipe Up to Unlock and Custom Text options don't work.

**To Reproduce**
1. Go to Settings -> Lynx -> Lockscreen
2. Enable "Hide Swipe Up to Unlock" or "Custom Text"
3. Respring

**Expected behavior**
The text should be hidden or changed.

**Screenshots**
![Screenshot of Lynx settings](https://user-images.githubusercontent.com/482367/110330649-4cc0a580-801e-11eb-9eb7-6acdf63d819c.png)
![Screenshot of lockscreen](https://femto.pw/sjzn)

**Platform (please complete the following information):**
 - Device: iPhone X
 - Injection: Substitute (checkra1n)
 - iOS Version: 14.3
 - Package Manager: Zebra

**Comment by SarahH12099** [comment]
Closed cause fixed
