### ISSUE TITLE
Table View Separators are always hidden

### ISSUE THREAD

**Issue by JiDoan** [MTACS/Lynx2#65]
**Describe the bug**

Table view separators are always hidden even if the option is off in the `System Wide` section.

**To Reproduce**

1. Turn off all options in `System Wide`
2. See table view separators hidden in Apps like Messages or Mail
3. Turn off Lynx
4. Table view separators are no longer hidden

**Expected behavior**

1. Table view separators aren't hidden if the option is not turned on 

**Screenshots**

**Platform (please complete the following information):**
 - Device: iPhone 12 mini
 - Injection: substitute
 - iOS Version: 14.2.1
 - Package Manager: Cydia

**Comment by JiDoan** [comment]
Also, resetting settings and turning Lynx back on still has the bug apparent

**Comment by MTACS** [comment]
Fixed in 2.0.6
