### ISSUE TITLE
Text on Passcodepage in one line

### ISSUE THREAD

**Issue by DarkZone-World** [MTACS/Lynx2#75]
**Describe the bug**
Text on the Passcode Page ( Swipe up for FaceID or enter Passcode) is in one line.

**To Reproduce**
Open Passcodepage on Lockscreen 

**Expected behavior**
Fix it to 2 Lines like this:
![4B6C877A-7363-4ADF-AD66-9410462A0707](https://user-images.githubusercontent.com/35103644/111886746-6d024400-89d0-11eb-8192-f569bccd378f.png)

**Screenshots**
![AB79DCA9-CA7E-4D1E-8EFC-03251D23B7B6](https://user-images.githubusercontent.com/35103644/111886713-14cb4200-89d0-11eb-8a0e-f3e2af46bf14.png)

**Platform (please complete the following information):**
 - Device: (iPhone XS)
 - Injection: (substrate)
 - iOS Version: (iOS 14.4)
 - Package Manager: (Cydia)

**Comment by MTACS** [comment]
Fixed in 2.0.6
