### ISSUE TITLE
Hide delete app in 3D Touch menu not working

### ISSUE THREAD

**Issue by KeyFlyz** [MTACS/Lynx2#80]
iPhone XS Max IOS 14.3
unc0ver v6.1.1
when turning on the option to hide "delete app" in 3D Touch menu it doesn't work it still shows in 3D Touch menu.
![image](https://user-images.githubusercontent.com/35471760/112099980-64e20a00-8b72-11eb-9a25-3e986c0cb40e.jpeg)
![image](https://user-images.githubusercontent.com/35471760/112100019-775c4380-8b72-11eb-9594-60bfcbcf978d.jpeg)

**Comment by SarahH12099** [comment]
Closing since is fixed.
