### ISSUE TITLE
Phone - Show Exact Time

### ISSUE THREAD

**Issue by abs0lut10n** [MTACS/Lynx2#84]
In “Phone”, when show exact time is enabled, “24 hours” option doesn’t work.
Only 12 hours is showed.

**Platform (please complete the following information):**
 - Device: (iPhone 11 Pro Max)
 - Injection: (Substitute)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Zebra, Cydia)

**Comment by rml9ty** [comment]
Push.

**Comment by MTACS** [comment]
Fixed in 2.1
