### ISSUE TITLE
Separators

### ISSUE THREAD

**Issue by abs0lut10n** [MTACS/Lynx2#85]
**Describe the bug**
Even when "Hide Separators" option in "System Wide section" is disabled, in the Mail app the separators are not shown

**Platform (please complete the following information):**
 - Device: (iPhone 11 Pro Max)
 - Injection: (substitute)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Zebra,Cydia)

**Comment by MTACS** [comment]
Wasn't able to reproduce, but fixed a separator issue in Messages that should also apply to Mail
