### ISSUE TITLE
status bar - hide status bar dot

### ISSUE THREAD

**Issue by tempest354** [MTACS/Lynx2#92]
![A7291239-1E81-44D3-8F77-1A6860585B7B](https://user-images.githubusercontent.com/81803667/113403730-150d0980-93e2-11eb-8576-4818a099a46f.jpeg)
![25D22346-1D58-4819-ACB0-2BC451955227](https://user-images.githubusercontent.com/81803667/113403740-1807fa00-93e2-11eb-9073-dfa00d0da278.png)
![D04DAD64-71A1-4D15-820A-E578D3CE35FE](https://user-images.githubusercontent.com/81803667/113403748-1a6a5400-93e2-11eb-8249-49812a1ce67d.png)
![388ECB5C-7B20-4D21-BE3C-48FCEE178EBF](https://user-images.githubusercontent.com/81803667/113403754-1f2f0800-93e2-11eb-91b3-c00d5f9fa09f.jpeg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Device: iphone 12 mini
 - Injection: libhooker
 - iOS Version: iOS 14.3
 - Package Manager: Sileo

When I use a phone call or voice memo, the dot on the upper right does not disappear. As I think the attached picture should not create a mole on the upper right. What's the cause?

**Comment by MTACS** [comment]
Fixed in 2.0.6
