### ISSUE TITLE
Crash after upgrading to Version 2.0.6-2

### ISSUE THREAD

**Issue by yuizen** [MTACS/Lynx2#95]
**Describe the bug**
After upgrading to latest version 2.0.6-2 whenever I open any app, my phone crashes and brings me to safe mode. Only solution is to downgrade to version 2.0.5. Tried deactivating all tweaks that I have and only Lynx 2 and still the same.

**To Reproduce**
Upgrade to version 2.0.6-2 open any app.

**Expected behavior**
Phone will crash and boot to safe mode.

**Platform (please complete the following information):**
 - Device: (iPhone XS Max)
 - Injection: (substrate, libhooker)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Cydia)
 - Jailbrok Tool: (unc0ver)

**Comment by MTACS** [comment]
Update pushed

**Comment by yuizen** [comment]
Issue fixed
