### ISSUE TITLE
2.0.6-2 crashes springboard

### ISSUE THREAD

**Issue by jwrulestheworld** [MTACS/Lynx2#96]
**Describe the bug**
Springboard crashes when I open an app with 2.0.6-2 installed

**To Reproduce**
1. Install upgrade
2. Open app
3. Springboard crashes
**Expected behavior**
The app should open

**Screenshots**
This is what Cr4shed says: https://imgur.com/gallery/0aaLU1l

**Platform (please complete the following information):**
 - Device: (iPhone X) 11 pro max
 - Injection: (substrate, libhooker) not sure, I use unc0ver though
 - iOS Version: (iOS 14.1) 14.1
 - Package Manager: (Zebra, Installer, Cydia, Sileo) zebra

**Comment by yuizen** [comment]
Same bug with my report #95
