### ISSUE TITLE
Switch off color

### ISSUE THREAD

**Issue by asherman07** [MTACS/Lynx2#97]
**Feature Request**
We have the ability to change the tint of switches when turned on but it would be nice to also have a tint for the off position as well.

**Comment by MTACS** [comment]
I wasn't able to get something to work for the off switch specifically, not sure if you meant the background but 2.0.8 has an option to tint the thumb which might interest you 
![image](https://user-images.githubusercontent.com/13209789/114046587-f631cb80-9856-11eb-891b-3d62e2010b3b.png)
