### ISSUE TITLE
Dock is so laggy everytime i open it

### ISSUE THREAD

**Issue by funny-awa** [MTACS/Lynx2#99]
**Describe the bug**
Every time i am in apps and go slipe up dock it goes laggy, i tested and it is lynx 2 the problem, just need to activate some option.

**To Reproduce**
Enter in some app and slipe up dock.

**Expected behavior**
Just go to dock, bruh.

**Screenshots**
I send a video.

https://user-images.githubusercontent.com/81269790/113648510-573c8200-9652-11eb-9abf-6ab7a8603358.mov

**Platform (please complete the following information):**
 - Device: iPad Pro (9,7) Dev Model:A1673
 - Injection: Substrate
 - iOS Version: iOS 14.3
 - Package Manager: Zebra

**Comment by SarahH12099** [comment]
Closed due to inactivity, no logs and no tweak list provided.
